const employees = [
  {
    id: 1,
    email: "employee1@company.com",
    password: "2308",
    tasks: [
      {
        active: true,
        newTask: true,
        completed: false,
        failed: false,
        title: "Design Landing Page",
        description: "Create landing page UI",
        date: "2026-01-16",
        category: "design",
      },
      {
        active: false,
        newTask: false,
        completed: true,
        failed: false,
        title: "Fix Navbar Bug",
        description: "Responsive navbar issue",
        date: "2026-01-12",
        category: "development",
      },
      {
        active: false,
        newTask: false,
        completed: false,
        failed: true,
        title: "Client Presentation",
        description: "Prepare slides",
        date: "2026-01-10",
        category: "management",
      },
    ],
  },

  {
    id: 2,
    email: "employee2@company.com",
    password: "2308",
    tasks: [
      {
        active: true,
        newTask: true,
        completed: false,
        failed: false,
        title: "API Integration",
        description: "Integrate login API",
        date: "2026-01-18",
        category: "development",
      },
      {
        active: false,
        newTask: false,
        completed: true,
        failed: false,
        title: "Code Review",
        description: "Review PRs",
        date: "2026-01-14",
        category: "development",
      },
      {
        active: false,
        newTask: false,
        completed: false,
        failed: true,
        title: "Deploy Build",
        description: "Production deployment",
        date: "2026-01-11",
        category: "devops",
      },
    ],
  },

  {
    id: 3,
    email: "employee3@company.com",
    password: "2308",
    tasks: [
      {
        active: true,
        newTask: true,
        completed: false,
        failed: false,
        title: "Create Wireframes",
        description: "Dashboard wireframes",
        date: "2026-01-17",
        category: "design",
      },
      {
        active: false,
        newTask: false,
        completed: true,
        failed: false,
        title: "User Research",
        description: "User interviews",
        date: "2026-01-13",
        category: "research",
      },
      {
        active: false,
        newTask: false,
        completed: false,
        failed: true,
        title: "Prototype Testing",
        description: "Test prototype",
        date: "2026-01-08",
        category: "testing",
      },
    ],
  },

  {
    id: 4,
    email: "employee4@company.com",
    password: "2308",
    tasks: [
      {
        active: true,
        newTask: true,
        completed: false,
        failed: false,
        title: "Database Schema",
        description: "Design DB schema",
        date: "2026-01-19",
        category: "backend",
      },
      {
        active: false,
        newTask: false,
        completed: true,
        failed: false,
        title: "Auth Module",
        description: "JWT auth system",
        date: "2026-01-15",
        category: "backend",
      },
      {
        active: false,
        newTask: false,
        completed: true,
        failed: false,
        title: "Optimize Queries",
        description: "Improve performance",
        date: "2026-01-12",
        category: "database",
      },
    ],
  },

  {
    id: 5,
    email: "employee5@company.com",
    password: "2308",
    tasks: [
      {
        active: true,
        newTask: true,
        completed: false,
        failed: false,
        title: "Write Test Cases",
        description: "Unit tests",
        date: "2026-01-20",
        category: "testing",
      },
      {
        active: false,
        newTask: false,
        completed: true,
        failed: false,
        title: "Regression Testing",
        description: "Test old features",
        date: "2026-01-14",
        category: "testing",
      },
      {
        active: false,
        newTask: false,
        completed: false,
        failed: true,
        title: "Automation Script",
        description: "Cypress setup",
        date: "2026-01-10",
        category: "automation",
      },
    ],
  },

  {
    id: 6,
    email: "employee6@company.com",
    password: "2308",
    tasks: [
      {
        active: true,
        newTask: true,
        completed: false,
        failed: false,
        title: "Create Blog UI",
        description: "Blog page UI",
        date: "2026-01-18",
        category: "frontend",
      },
      {
        active: false,
        newTask: false,
        completed: true,
        failed: false,
        title: "CSS Refactor",
        description: "Improve styles",
        date: "2026-01-13",
        category: "frontend",
      },
      {
        active: false,
        newTask: false,
        completed: false,
        failed: true,
        title: "Animation Bug",
        description: "GSAP bug fix",
        date: "2026-01-09",
        category: "frontend",
      },
    ],
  },

  {
    id: 7,
    email: "employee7@company.com",
    password: "2308",
    tasks: [
      {
        active: true,
        newTask: true,
        completed: false,
        failed: false,
        title: "SEO Optimization",
        description: "Improve SEO score",
        date: "2026-01-21",
        category: "seo",
      },
      {
        active: false,
        newTask: false,
        completed: true,
        failed: false,
        title: "Meta Tags",
        description: "Add meta tags",
        date: "2026-01-15",
        category: "seo",
      },
      {
        active: false,
        newTask: false,
        completed: false,
        failed: true,
        title: "Analytics Setup",
        description: "GA configuration",
        date: "2026-01-11",
        category: "marketing",
      },
    ],
  },

  {
    id: 8,
    email: "employee8@company.com",
    password: "2308",
    tasks: [
      {
        active: true,
        newTask: true,
        completed: false,
        failed: false,
        title: "Cloud Backup",
        description: "Setup backups",
        date: "2026-01-22",
        category: "devops",
      },
      {
        active: false,
        newTask: false,
        completed: true,
        failed: false,
        title: "Server Monitoring",
        description: "Configure alerts",
        date: "2026-01-16",
        category: "devops",
      },
      {
        active: false,
        newTask: false,
        completed: false,
        failed: true,
        title: "Docker Build",
        description: "Docker image build",
        date: "2026-01-12",
        category: "devops",
      },
    ],
  },

  {
    id: 9,
    email: "employee9@company.com",
    password: "2308",
    tasks: [
      {
        active: true,
        newTask: true,
        completed: false,
        failed: false,
        title: "Content Writing",
        description: "Write homepage content",
        date: "2026-01-19",
        category: "content",
      },
      {
        active: false,
        newTask: false,
        completed: true,
        failed: false,
        title: "Proof Reading",
        description: "Fix grammar",
        date: "2026-01-14",
        category: "content",
      },
      {
        active: false,
        newTask: false,
        completed: false,
        failed: true,
        title: "Blog Draft",
        description: "Draft rejected",
        date: "2026-01-10",
        category: "content",
      },
    ],
  },

  {
    id: 10,
    email: "employee10@company.com",
    password: "2308",
    tasks: [
      {
        active: true,
        newTask: true,
        completed: false,
        failed: false,
        title: "HR Documentation",
        description: "Update employee docs",
        date: "2026-01-23",
        category: "hr",
      },
      {
        active: false,
        newTask: false,
        completed: true,
        failed: false,
        title: "Onboarding Process",
        description: "New hires onboarding",
        date: "2026-01-17",
        category: "hr",
      },
      {
        active: false,
        newTask: false,
        completed: false,
        failed: true,
        title: "Policy Review",
        description: "Missed deadline",
        date: "2026-01-11",
        category: "hr",
      },
    ],
  },
];

const admin = [{ id: 1, email: "admin@company.com", password: "2308" }];

export const setLocalStorage = () => {
  localStorage.setItem("employees", JSON.stringify(employees));
  localStorage.setItem("admin", JSON.stringify(admin));
};

export const getLocalStorage = () => {
  const employees = JSON.parse(localStorage.getItem("employees"));
  const admin = JSON.parse(localStorage.getItem("admin"));
};
